Data callbacks
whoshuu/cpr pull request #446
Opened 2020-09-21 16:02 UTC by xloem

This a separate PR for my work on #443 .  More description at https://github.com/ITotalJustice/cpr/pull/1 .  Let me know if you'd like a rebase.

I'm realizing that my removal of ITotalJustice's custom structs makes it more difficult to add functionality to fill the Response fields simultaneous with using the callback functions.  That's unfortunate, but this is what I have implemented at this time.

2020-09-22 08:44 UTC, COM8 requested changes
Great work. Thanks!
Only a few minor changes.

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +    void SetProgressCallback(const ProgressCallback& parameters);
```suggestion
    void SetProgressCallback(const ProgressCallback& progress);
```

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +        readcb_ = read;
```suggestion
    if (curl) {
        readcb_ = read;
        curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE,
                         static_cast<curl_off_t>(read.size));
        curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE_LARGE,
                         static_cast<curl_off_t>(read.size));
        curl_easy_setopt(curl, CURLOPT_READFUNCTION, cpr::util::readUserFunction);
        curl_easy_setopt(curl, CURLOPT_READDATA, &readcb_);
        if (read.size == -1) {
            SetHeader({{"Transfer-Encoding", "chunked"}});
        }
```
Better readability.

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +        headercb_ = header;
```suggestion
        headercb_ = header;
        curl_easy_setopt(curl, CURLOPT_HEADERDATA, &headercb_);
```

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +        writecb_ = write;
```suggestion
        writecb_ = write;
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &writecb_);
```

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +    }
```suggestion
    if (curl) {
        progresscb_ = progress;
        #if LIBCURL_VERSION_NUM < 0x072000
        curl_easy_setopt(curl, CURLOPT_PROGRESSFUNCTION, cpr::util::progressUserFunction);
        curl_easy_setopt(curl, CURLOPT_PROGRESSDATA, &progresscb_);
        #else
        curl_easy_setopt(curl, CURLOPT_XFERINFOFUNCTION, cpr::util::progressUserFunction);
        curl_easy_setopt(curl, CURLOPT_XFERINFODATA, &progresscb_);
        #endif
        curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);
    }
```

2020-09-22 08:44 UTC, COM8 commented on cpr/session.cpp
> +        debugcb_ = debug;
```suggestion
        debugcb_ = debug;
        curl_easy_setopt(curl, CURLOPT_DEBUGDATA, &debugcb_);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
```

2020-09-22 08:46 UTC, COM8 commented
The following needs to be fixed for the windows CI to run:
```
D:\a\cpr\cpr\include\cpr/callback.h(14,93): error C2614: 'cpr::ReadCallback': illegal member initialization: 'size' is not a base or member [D:\a\cpr\cpr\build\cpr\cpr.vcxproj]
```
Source: https://github.com/whoshuu/cpr/pull/446/checks?check_run_id=1144990491

2020-09-22 17:30 UTC, xloem commented
It looks like the CI failure is from windows not having `ssize_t`.  I (or somebody) will have to evaluate the context of use again and either pick a different type or accommodate windows.  There's probably a type already used similarly in cpr in other places.  Makes sense to add the clarity suggestions at the same time.

2020-09-23 08:12 UTC, COM8 commented
Windows does not know the `ssize_t` type. I will push a quick fix for this.

2020-09-23 08:24 UTC, COM8 approved these changes

2020-09-23 08:54 UTC, merged

2020-09-23 16:38 UTC, xloem commented
Thanks for pulling in all this stuff com8, we can all celebrate.