Updated docs for #446
whoshuu/cpr pull request #447
Opened 2020-09-21 16:05 UTC by xloem

A separate PR for my work in #434

2020-09-22 08:58 UTC, COM8 requested changes
Nice documentation. Thanks!
Only a few things and we are ready to go here.

2020-09-22 08:58 UTC, COM8 commented on advanced-usage.md
> +Return `true` on success, or `false` to cancel the transfer.
```suggestion
Return `true` on success, or `false` to **cancel** the transfer.
```

2020-09-22 08:58 UTC, COM8 commented on advanced-usage.md
> +Return `true` on success, or `false` to cancel the transfer.
```suggestion
Return `true` on success, or `false` to **cancel** the transfer.
```

2020-09-22 08:58 UTC, COM8 commented on advanced-usage.md
> +Return `true` on success, or `false` to cancel the transfer.
```suggestion
Return `true` on success, or `false` to **cancel** the transfer.
```

2020-09-22 08:58 UTC, COM8 commented on advanced-usage.md
> +The values are in bytes.  Return `true` to continue the transfer, and `false` to cancel it.
```suggestion
The values are in bytes.  Return `true` to continue the transfer, and `false` to **cancel** it.
```

2020-09-22 08:58 UTC, COM8 commented on advanced-usage.md
> +int main(int argc, char **argv) {
```suggestion
int main(int argc, char** argv) {
```

2020-09-22 17:18 UTC, xloem commented
Minor changes look great.  Feel free to add them in yourself, or I will in some time.

2020-09-23 08:23 UTC, COM8 approved these changes

2020-09-23 08:54 UTC, merged