Documentation for PinnedPublicKey #575
whoshuu/cpr pull request #577
Opened 2021-06-05 05:14 UTC by alysondeives

Documentation for PR #575

2021-06-07 13:26 UTC, COM8 requested changes
Nice documentation.

2021-06-07 13:26 UTC, COM8 commented on advanced-usage.md
> +`libcurl` will abort the connection before sending or receiving any data.
```suggestion
`libcurl` (and therefore `CPR`) will abort the connection before sending or receiving any data.
```

2021-06-07 13:26 UTC, COM8 commented on advanced-usage.md
> +``` bash
Nice addition 👍.

2021-06-07 23:20 UTC, alysondeives commented
> Nice documentation.

Thanks. I extracted it from curl doc

https://curl.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html

2021-06-08 13:19 UTC, COM8 approved these changes

2021-06-08 13:19 UTC, merged