add interface GetDownloadFileLength
whoshuu/cpr pull request #599
Opened 2021-07-27 07:57 UTC by zydxhs

Some HTTP servers don't support the HEAD method to get the length of the file, so I added the GetDownloadFileLength interface to get the length of the file before the actual download starts. 

Unnecessary memory allocation can be avoided in some scenarios.

example :
``` c++
void *global_buff = nullptr;
int64_t global_down_length = 0;

bool write_data(std::string data)
{
    memcpy(global_buff + global_down_length, data.data(), data.size());
    global_down_length += data.size();
}

int main() {
    cpr::Session session;
    session.SetUrl(cpr::Url{"http://xxx/file"});
    // memory alloc
    global_buff = malloc(session.GetDownloadFileLength());
    session.Download(cpr::WriteCallback{write_data});
    // do something
    free(global_buff);
    global_buff = nullptr;
}
```

2021-07-27 12:20 UTC, COM8 requested changes
Good idea!
Thanks.
Please replace `int64_t` with `cpr_off_t`, which is defined here:
https://github.com/whoshuu/cpr/blob/cfb2a3e42e10e5a1a6e16de22504740b6ab1c6ad/include/cpr/cprtypes.h#L13-L16

It is a simple wrapper for `curl_off_t` to prevent applications from having to link against libcurl.

Besides that, please create an additional PR for documentation against the `gh-pages` branche.

2021-07-27 12:20 UTC, COM8 commented on cpr/session.cpp
> +    int64_t GetDownloadFileLength();
```suggestion
    cpr_off_t GetDownloadFileLength();
```

2021-07-27 12:20 UTC, COM8 commented on cpr/session.cpp
> +int64_t Session::Impl::GetDownloadFileLength() {
```suggestion
cpr_off_t Session::Impl::GetDownloadFileLength() {
```

2021-07-27 12:20 UTC, COM8 commented on cpr/session.cpp
> +	curl_off_t downloadFileLenth = -1;
```suggestion
	cpr_off_t downloadFileLenth = -1;
```

2021-07-27 12:20 UTC, COM8 commented on cpr/session.cpp
> +int64_t Session::GetDownloadFileLength() { return pimpl_->GetDownloadFileLength(); }
```suggestion
cpr_off_t Session::GetDownloadFileLength() { return pimpl_->GetDownloadFileLength(); }
```

2021-07-27 12:20 UTC, COM8 commented on include/cpr/session.h
> +    int64_t GetDownloadFileLength();
```suggestion
    cpr_off_t GetDownloadFileLength();
```

2021-07-29 02:59 UTC, zydxhs commented
Now I have changed int64_t/curl_off_t to cpr_off_t.

2021-07-29 06:25 UTC, COM8 commented
`ubuntu-18-gcc-shared-ssl-system-curl` and `ubuntu-18-gcc-static-ssl-system-curl` are currently expected to fail.

2021-07-29 06:40 UTC, COM8 approved these changes

2021-07-29 09:01 UTC, zydxhs commented
> `ubuntu-18-gcc-shared-ssl-system-curl` and `ubuntu-18-gcc-static-ssl-system-curl` are currently expected to fail.

@COM8 Please tell me, what should I do?

2021-07-31 12:31 UTC, COM8 commented
> > `ubuntu-18-gcc-shared-ssl-system-curl` and `ubuntu-18-gcc-static-ssl-system-curl` are currently expected to fail.
> 
> @COM8 Please tell me, what should I do?

Nothing. They are broken. It should fix it self.

> 
> > Besides that, please create an additional PR for documentation against the gh-pages branche.
> 
> I didn't find the documentation for the Download interface in gh-pages, how should I add it?

Please create a `DOWNLOAD Requests` section next to the [`PUT and PATCH Requests`](https://whoshuu.github.io/cpr/advanced-usage.html#put-and-patch-requests) section. Add a small download example and then in a sub-section add your example and documentation.

2021-08-12 07:33 UTC, merged