add userdata param to callback function
whoshuu/cpr pull request #601
Opened 2021-07-29 08:48 UTC by zydxhs

Add UserData to the callback function to satisfy concurrent calls in a multi-threaded environment, and put the userdata parameter last.

2021-07-31 12:21 UTC, COM8 requested changes
Looks good. Only those two small variable reordering changes required.

2021-07-31 12:21 UTC, COM8 commented on test/callback_tests.cpp
> +    Response response = Post(url, ProgressCallback{[](intptr_t /*userdata*/, size_t /*downloadTotal*/, size_t /*downloadNow*/, size_t /*uploadTotal*/, size_t /*uploadNow*/) -> bool { return false; }}
```suggestion
    Response response = Post(url, ProgressCallback{[](size_t /*downloadTotal*/, size_t /*downloadNow*/, size_t /*uploadTotal*/, size_t /*uploadNow*/, intptr_t /*userdata*/) -> bool { return false; }});
```

2021-07-31 12:21 UTC, COM8 commented on test/callback_tests.cpp
> +    Response response = Post(url, ProgressCallback{[](intptr_t /*userdata*/, size_t /*downloadTotal*/, size_t /*downloadNow*/, size_t /*uploadTotal*/, size_t /*uploadNow*/) -> bool { return false; }}
Probably the wrong order.

2021-07-31 12:21 UTC, COM8 commented on test/callback_tests.cpp
> +    Response response = Post(url, body, ProgressCallback{[&](intptr_t /*userdata*/, size_t downloadTotal, size_t /*downloadNow*/, size_t uploadTotal, size_t /*uploadNow*/) -> bool {
```suggestion
    Response response = Post(url, body, ProgressCallback{[&](size_t downloadTotal, size_t /*downloadNow*/, size_t uploadTotal, size_t /*uploadNow*/, intptr_t /*userdata*/) -> bool {
```

2021-07-31 12:22 UTC, COM8 commented
Docs: https://github.com/whoshuu/cpr/pull/600

2021-08-02 03:16 UTC, zydxhs commented
I'm really sorry for the extra work caused by my mistake.

I have fixed the error.

2021-08-02 03:19 UTC, zydxhs commented
I'm really sorry for the extra work caused by my mistake.

I have fixed the error.

2021-08-02 06:14 UTC, COM8 approved these changes

2021-08-02 06:23 UTC, merged

2021-08-02 06:24 UTC, COM8 commented
Thanks for your time with this PR!

2022-07-22 18:26 UTC, Chronial commented
I am somewhat confused by this API-Breaking change: What is the point of the userdata parameter? The callback is a std::function and can thus contain arbitrary data / state.

What is the difference between `cpr::ReadCallback{-1, [userdata = 23](char*, size_t& ) -> size_t { ... }}` 
and the new infertace `cpr::ReadCallback{-1, [](char*, size_t&, intptr_t userdata) -> size_t { ... }, 23}` ?

2022-07-25 08:43 UTC, COM8 commented
Hmmm, I have to agree. This should have been solvable without this additional parameter. @zydxhs is there any specific use case, which prevents your use case from using the `std::function` capture?