add document for Download
whoshuu/cpr pull request #604
Opened 2021-08-03 01:42 UTC by zydxhs

This PR is the document for PR #599.

2021-08-09 07:19 UTC, COM8 requested changes
Thanks for taking the time to add the documentation here.
Only two small things to fix and we are ready to go.

2021-08-09 07:19 UTC, COM8 commented on advanced-usage.md
> +    void *  file_buf;  // file data will be save to
```suggestion
    void*  file_buf;  // file data will be save to
```

2021-08-09 07:19 UTC, COM8 commented on advanced-usage.md
> +    File *pf = (File *)userdata;
```suggestion
    File* pf = static_cast<File*>(userdata);
```

2021-08-12 03:18 UTC, zydxhs commented
The pointer's position fixed.

2021-08-12 07:32 UTC, COM8 approved these changes
Thanks!

2021-08-12 07:33 UTC, merged